export const CHANGE_INPUT_VALUE='change_input_value'
export const ADDITEM='add_item'
export const DELECT_ITEM='delect_item'
export const GET_LIST_DATA='getListData'
export const GET_LIST_ACTION='getListAction'
export const GET_MY_LIST ='getMyList'